# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Naman Jain's blog
email: nmn.jain1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Articles about my experiences working with Java
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.naman.ninja" # the base hostname & protocol for your site
twitter_username: namanbmiet
github_username:  naman90

# Build settings
markdown: kramdown
